### ISSUE TITLE
Handle non-200 responses correctly in cache-crawler

### ISSUE THREAD

**Issue by SaFrMo** [funkhaus/vuepress#100]
![Screenshot showing 401 and JSON errors](https://user-images.githubusercontent.com/5344587/38515050-ffeec5f2-3c00-11e8-9f06-72c449189b76.png)

If cache-crawler receives a non-200 response from a fetch request, it'll still cache the result, leading to broken sites. 

We should make it check the response status and make sure it's an acceptable value before caching the response. Otherwise, the crawler should skip this entry and continue to the next.

**Comment by johndigital** [comment]
That's a very good call! Might be good to have just a generalized try/catch statement in there to prevent the cache crawler from throwing errors entirely. Since the whole function of it is non-essential, it should probably just fail silently if anything goes wrong during its process.

**Comment by drewbaker** [comment]
Would be handy if it did a `console.log()` of the URL giving the issue. I've actually found it to be useful for catching bad links my code. Like seeing a `bernards.local/false` in the console actually helped me, but it shouldn't be cached or throw an error.

**Comment by SaFrMo** [comment]
Fixed in 620ea11! A couple notes:

1. There's an `ignorePath` check [here](https://github.com/funkhaus/vuepress/blob/master/src/utils/cache-crawler.js#L61-L65) that handles the most common broken-path scenarios, but it won't catch all of them. Let's keep adding to this in the boilerplate when we find other conditions.
1. There's nothing we can do, as far as I'm aware, about fetching a broken URL, having it throw a 401, 404, etc error, and logging that error to the console. I didn't add the `log` suggestion you mentioned @drewbaker because of this.

Going to keep this issue open for a couple days more to make sure it's seen!
