### ISSUE TITLE
Consider adding a code formatter

### ISSUE THREAD

**Issue by johndigital** [funkhaus/vuepress#101]
Might be worth adding something like this into our webpack process so we all have the same formatting: https://prettier.io/

**Comment by drewbaker** [comment]
I would love this. I think style/formatting is so important for readability, it would be great to enforce it accross the team. I worry way too much about `this(){}` vs `this (){}`!

**Comment by johndigital** [comment]
This has now been added! 3295282ff20045bcc74a91d80b14416efddacd37
