### ISSUE TITLE
Add dynamic version number to index.php stylesheet link

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/vuepress#107]
Current theme has this line in `<head>` which means clients complain about cached CSS more than the otherwise should:
```
<link rel="stylesheet" type="text/css" media="all" href="<?php echo get_template_directory_uri(); ?>/static/bundle.css?ver=1.0" />
```

We should make that version number be dynamic based on file `custom_latest_timestamp()`. I think it might be as easy as this, but I'm not sure if that factors in the .css file or just the .js file timestamps.
```
<link rel="stylesheet" type="text/css" media="all" href="<?php echo get_template_directory_uri(); ?>/static/bundle.css?ver=<?php echo custom_latest_timestamp(); ?>" />
```

**Comment by johndigital** [comment]
This has been implemented for a while! https://github.com/funkhaus/vuepress/blob/master/index.php#L18
