### ISSUE TITLE
Prerendering

### ISSUE THREAD

**Issue by mfissehaye** [funkhaus/vuepress#111]
I am trying to prerender my page.
I integrated prerender-spa-plugin. It is great. But now that I have to use an index.html file in the theme folder.
But there is only index.php. If I rewrite the php functionality and rename the file to index.html, I will lose all the imports and dynamic title and meta stuff.

My intention is SEO by the way. The crawler couldn't find content in my page.

What do you suggest?

**Comment by drewbaker** [comment]
Hmmm... I’d try to get that plugin changed to work with index.php files, I’m sure that wouldn’t be too big of a change for them. 

But depending on the type of server you are using, and the access you have to it, there are some solutions here that might work. The idea is to get the server to allow PHP to run in HTML files. 
https://stackoverflow.com/questions/22853669/how-to-run-a-php-script-inside-a-html-file

**Comment by SaFrMo** [comment]
@mfissehaye Any luck getting prerendering to work? We've got this in the back of our minds lately too, although like John said, SEO hasn't been too different on our end even with dynamic sites. Thanks!

**Comment by SaFrMo** [comment]
Going to close this issue for now - let us know if there are any updates we should know about @mfissehaye!
