### ISSUE TITLE
Build error on Windows

### ISSUE THREAD

**Issue by SaFrMo** [funkhaus/vuepress#113]
On Windows 7, running `npm run build` throws an error saying `NODE_ENV is not recognized as an internal or external command, operable program or batch file`. This'd be an important fix for Windows users!

**Comment by drewbaker** [comment]
The fix is to just install OSX. 😜

Man I wish Apple cared about games!

**Comment by johndigital** [comment]
Looks like this package might be the most "correct" way to solve this: https://www.npmjs.com/package/cross-env

**Comment by SaFrMo** [comment]
Added this fix in 6571bad
