### ISSUE TITLE
Remove .default from register of Vue.component 

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/vuepress#118]
In main.js do we need the .default anymore?

`Vue.component('transition-fade', require('fh-components/transition-fade').default)`

I think it can just be:

`Vue.component('transition-fade', require('fh-components/transition-fade'))`

Right?

**Comment by SaFrMo** [comment]
That's right! I'll update this, the fh-components version, and the boilerplate for new components or directives later today.

**Comment by SaFrMo** [comment]
Fixed in 8fbbf8e
