### ISSUE TITLE
Clean up router.php?

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/vuepress#119]
What do you guys think of this:

We rename vp-plugins.php to be vp-functions.php, then we move these lines into a function in vp-functions.php. Probably call that function `get_custom_template_routes()`.
https://github.com/funkhaus/vuepress/blob/master/functions/router.php#L8-L37

Then this line:
https://github.com/funkhaus/vuepress/blob/master/functions/router.php#L79

Would be come:
`$jsonData['routes'] = array_merge( get_custom_template_routes(), $programmed_routes );`

**Comment by johndigital** [comment]
Yea, I think this is a great idea. Would be really helpful to keep that file as clean as possible!

**Comment by drewbaker** [comment]
OK I'm doing it now.

**Comment by drewbaker** [comment]
Implemented with https://github.com/funkhaus/vuepress/commit/9adbf3cdcde3426455848fcce19f8f5d1d2c18c0
