### ISSUE TITLE
Dynamically set Open Graph meta tags?

### ISSUE THREAD

**Issue by garrethpxy** [funkhaus/vuepress#122]
Hi there, thanks for the fantastic boilerplate. Loving the ability to build my blog in VueJS!

How should I go about setting up open graph meta tags like `og:title` dynamically? Do I need modify some wordpress PHP code or would it be possible to download a plugin compatible with vuepress to achieve this?

**Comment by drewbaker** [comment]
Thanks @garrethpxy! Glad you like it!

You can change the code of those OG tags in this file. It is PHP.
https://github.com/funkhaus/vuepress/blob/master/parts/og-tags.php

But I don't think you'd need to change the OG title dynamically, because whenever the scraper goes to read the OG tags, they will be accurate to the scraper.

**Comment by garrethpxy** [comment]
hi @drewbaker, thanks for the reply! 
Hmm, what i'm trying to achieve is actually to set a specific `og: image` for pages
I'd like to use ACF to set an image for a particular page, but i'm not sure how to hook that up so that `og:image` would use that image. 

This is so that facebook/twitter to display that image in the link when it is shared.

Appreciate any advice you may have!

**Comment by drewbaker** [comment]
Yeah it shouldn’t be too hard to do that. Currently the og:image will be set to the featured image. If you want to have that image come out of ACF instead, it should be really easy to change that in the og-tags.php file. 

Send me a screenshot of the acf settings for that image input and I could probably give you the code for og-tags.

**Comment by garrethpxy** [comment]
Sure, here is the ACF setting
![image](https://user-images.githubusercontent.com/7438517/43796887-2477fd7e-9ab8-11e8-9407-6ffcf0ebab7f.png)

which outputs this in the loop:
![image](https://user-images.githubusercontent.com/7438517/43796984-70f85266-9ab8-11e8-8a4e-63dac495594b.png)

Is this what you need?

**Comment by garrethpxy** [comment]
hi @drewbaker, just following up on my last comment. Is the information i provided what you expected? Thanks in advance!

**Comment by drewbaker** [comment]
Yeah so you just want to change the "Return value" to be image ID, then in `og-tags.php` on line 8, change this line:

```
            $image_id = get_post_thumbnail_id();
```

To this:


```
            $image_id = $post->main_image;
```

And that should do it.

**Comment by garrethpxy** [comment]
@drewbaker, thanks much for your help! This works well. I'll close this issue now
