### ISSUE TITLE
Navigating to page does not change <title>

### ISSUE THREAD

**Issue by garrethpxy** [funkhaus/vuepress#123]
When I navigate to a page, say `mysite.local/about`, which has a Page Title of `About`, I expect the `<title>` meta tag inside head to become `About | [Site Title]`, or similar.

Right now, it remains static no matter which page i go to, reflecting only `[Site Title]`

This is confusing for navigation, since the history shows a list of pages with the exact same title.

How can I modify the boilerplate to support changing <title> on navigation? Should i be tweaking the router or `index.php`?

**Comment by johndigital** [comment]
Hey @garrethpxy !

In the latest version of vuepress this should be handled [automatically by this function](https://github.com/funkhaus/vuepress/blob/master/src/App.vue#L41-L46).

With everything at its default, this should run each time the page changes and replace the current document title with the correct title of the incoming page. Here is an example of a recent site of ours with this logic implemented, you can see that the title changes page to page: https://imagine-entertainment.com

The "incoming title" of any given page is set via the `wp_title()` function so it can be easily modified with this hook: https://developer.wordpress.org/reference/hooks/wp_title/

**Comment by garrethpxy** [comment]
hi @johndigital! thanks much for the detailed response. You were right, everything was handled as you described. I was facing the issue as I had accidentally defined a duplicate `watch` property in `App.vue`, which overwrote the watcher that changed the title when `state.meta.title` changed (doh!)

I'll mark this as resolved as it was a mistake on my part! Thanks once again.

**Comment by johndigital** [comment]
Great! Glad this is resolved and thank you for following up to let me know.
