### ISSUE TITLE
Make og-tags.php work with screenshot.png or .jpg

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/vuepress#124]
Currently the og-tags.php file only works with screenshot.png, but sometimes we upload a .jpg instead, and forget to change the code. We should make it check for the .png, and if not there, fallback to a .jpg extension.

**Comment by drewbaker** [comment]
We also need to fix this on schema.php too.

**Comment by SaFrMo** [comment]
Added in 12353af!
