### ISSUE TITLE
Problem with npm install/dev

### ISSUE THREAD

**Issue by Vitaliz** [funkhaus/vuepress#125]
Hello.
I tried to build a template as described in Wiki, but I get error.
![image](https://user-images.githubusercontent.com/5803161/45113982-03a1e900-b176-11e8-8e0f-79136f9d8b82.png)

Here is this .log file:

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@5.6.0
3 info using node@v8.11.4
4 verbose npm-session 28a6b4472cd4aace
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall vuepress@1.1.5
7 info lifecycle vuepress@1.1.5~preinstall: vuepress@1.1.5
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly saveTree vuepress@1.1.5
14 verbose stack SyntaxError: Unexpected token < in JSON at position 105553
14 verbose stack     at JSON.parse (<anonymous>)
14 verbose stack     at module.exports (D:\Program Files\nodejs\node_modules\npm\lib\utils\parse-json.js:3:15)
14 verbose stack     at BB.join (D:\Program Files\nodejs\node_modules\npm\lib\install\read-shrinkwrap.js:31:20)
14 verbose stack     at tryCatcher (D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
14 verbose stack     at Holder$3._callFunction (eval at generateHolderClass (D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\join.js:92:16), <anonymous>:14:44)
14 verbose stack     at Holder$3.checkFulfillment (eval at generateHolderClass (D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\join.js:92:16), <anonymous>:29:30)
14 verbose stack     at Promise.eval (eval at thenCallback (D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\join.js:14:16), <anonymous>:6:20)
14 verbose stack     at Promise._settlePromise (D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:566:21)
14 verbose stack     at Promise._settlePromise0 (D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
14 verbose stack     at Promise._settlePromises (D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
14 verbose stack     at Promise._fulfill (D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:638:18)
14 verbose stack     at Promise._settlePromise (D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:582:21)
14 verbose stack     at Promise._settlePromise0 (D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
14 verbose stack     at Promise._settlePromises (D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
14 verbose stack     at Promise._fulfill (D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:638:18)
14 verbose stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\nodeback.js:42:21
15 verbose cwd D:\xampp\htdocs\wp\wp-content\themes\vuepress-basic
16 verbose Windows_NT 10.0.17134
17 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
18 verbose node v8.11.4
19 verbose npm  v5.6.0
20 error Unexpected token < in JSON at position 105553
21 verbose exit [ 1, true ]

How can I fix this issue?
Thank for your Vuepress,  I really need to get a working version

Vitaly.

**Comment by SaFrMo** [comment]
Hi Vitaly, thanks for the issue! Did you take a look at [this similar bug](https://github.com/npm/npm/issues/17340)? Basically, try removing `package-lock.json` and installing again. Let us know if that works or you're still getting problems!

**Comment by Vitaliz** [comment]
Hi SaFrMo. Thanks for advice, I had remove `package-lock.json` and installing again. But I get many errors and warnings. 
![image](https://user-images.githubusercontent.com/5803161/45221551-f737a080-b2db-11e8-9843-5bb1f4a09dcd.png)
I think one of the reasons for this issue is The blocking of some Amazone resources in Russia during Telegram messenger blocking((
And I see npm try to find Python on my PC? I don't install it yet...

**Comment by SaFrMo** [comment]
Hmm, weird! Those look like node-sass errors - do you have Windows build tools installed? [This answer](https://stackoverflow.com/a/46977724) might help!

**Comment by Vitaliz** [comment]
Thanks. I`ll check my environment

**Comment by SaFrMo** [comment]
@Vitaliz Any update on this? Hopefully it's looking better!

**Comment by SaFrMo** [comment]
@Vitaliz Closing for now, but do let us know and reopen if you're still experiencing the issue!
