### ISSUE TITLE
Woo Commerce Plugin

### ISSUE THREAD

**Issue by mrkylemac** [funkhaus/vuepress#126]
I'm wondering why I can't add WooCommerce to Vuepress? If I activate another theme then the WooCommerce plugin appears whereas, when Vuepress theme is active -- the Woo Commerce is active although isn't visible on the admin sidebar, nor can I access the WC plugin settings option.

Any ideas?

**Comment by SaFrMo** [comment]
Thanks for the issue! We don't use WooCommerce too much here, but I'll do my best to help. What version of WordPress are you using? Are there any logs you can find?

I tried installing WooCommerce on a local site and ran into a similar issue with the Vuepress theme, but for me, the WooCommerce settings page wasn't accessible even when a different theme was activated. Had you already set up WC on your site before adding the Vuepress theme?

**Comment by mrkylemac** [comment]
Appreciate you looking into this Sander!

Installing/setup of WC before activating VUEPRESS theme and installing required plugins works! until I tried adding a new product.

Then I recieved this new permissions error: 
https://jmp.sh/lxygfMB

And then WC disappeared from the admin sidebar with WC plugin settings link, back to same error:
https://jmp.sh/6LfSLmG

Wordpress version: 4.9.8
PHP version: 7.1.7
SQL version: 5.6.40

Does this give you any extra clues?

**Comment by mrkylemac** [comment]
I created a new user with a 'shop manager' role and WC works as desired!

![mrkylemac 2018-09-07 at 9 49 16 am](https://user-images.githubusercontent.com/3252504/45190867-78167e00-b283-11e8-9c27-e952f0ef3d65.jpg)

**Comment by SaFrMo** [comment]
Ahh, got it - thanks for the info, this is super helpful! The problem here is Vuepress creating the role "Developer" to keep clients separate from the `dev-id` fields. See [this section](https://github.com/funkhaus/vuepress#the-developer-role-and-developer-ids) in the readme for more details. I'll look into a fix for this right away!

**Comment by SaFrMo** [comment]
OK, got a fix for you!

Copy and paste the lines below wherever you'd like in a .php file - I did mine at the bottom of `functions/developer-role.php`.

```php

    // add extra capabilities for common plugins
    function add_extra_vp_capabilities(){
        global $wp_roles;

        // add desired developer capabilities here
        $caps_to_add = array(
            'manage_woocommerce',
            'view_woocommerce_reports'
        );

        // woocommerce defaults
        // (https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-install.php#L981)
        $capability_types = array( 'product', 'shop_order', 'shop_coupon' );
        foreach ( $capability_types as $capability_type ) {
            $wc_caps_to_add = array(
                // Post type.
                "edit_{$capability_type}",
                "read_{$capability_type}",
                "delete_{$capability_type}",
                "edit_{$capability_type}s",
                "edit_others_{$capability_type}s",
                "publish_{$capability_type}s",
                "read_private_{$capability_type}s",
                "delete_{$capability_type}s",
                "delete_private_{$capability_type}s",
                "delete_published_{$capability_type}s",
                "delete_others_{$capability_type}s",
                "edit_private_{$capability_type}s",
                "edit_published_{$capability_type}s",
                // Terms.
                "manage_{$capability_type}_terms",
                "edit_{$capability_type}_terms",
                "delete_{$capability_type}_terms",
                "assign_{$capability_type}_terms",
            );

            foreach($wc_caps_to_add as $wc_cap_to_add){
                $caps_to_add[] = $wc_cap_to_add;
            }
        }

        // get developer role
        $developer_role = get_role('developer');

        // add desired caps to developer if they don't exist yet
        foreach($caps_to_add as $cap_to_add){
            if( !$developer_role->has_cap($cap_to_add) ){
                $wp_roles->add_cap( 'developer', $cap_to_add );
            }
        }
    }
    add_action('after_switch_theme', 'add_extra_vp_capabilities');
```

Then switch to a theme other than Vuepress and then back again. If that doesn't work, switch themes off and on again one more time.

This function adds WooCommerce capabilities to the Developer role, which should fix your issues! I'll add to the boilerplate once you've confirmed it works so other users don't run into this problem.

**Comment by mrkylemac** [comment]
Awesome Sander, WC appeared after a couple of switches!

Thanks again for the quick help, loving this boilerplate for my current projects...

**Comment by SaFrMo** [comment]
You're very welcome! Glad you're enjoying the boilerplate - let us know if there are any other issues you run into!
