### ISSUE TITLE
Add sample filter to theme. 

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/vuepress#14]
Good idea to add a filter showing how to add all attachments to the home page

**Comment by drewbaker** [comment]
A really good idea here would be attachments and video embeds based off the default video meta field

**Comment by drewbaker** [comment]
```
    // Get the iFrame embed code
    function custom_video_embed($input){

        if( isset($input['meta']['custom_video_url']) ) {
            $args = array(
                'width' => 1280
            );
            $embed = wp_oembed_get($input['meta']['custom_video_url'], $args);

            $input['meta']['custom_video_url_embed'] = $embed;
        }

        return $input;
    }
    add_filter('rez_serialize_post', 'custom_video_embed');
```

**Comment by SaFrMo** [comment]
@drewbaker We'll be adding all attachments in Rest-Easy soon, so I didn't include that example, but I did include that `custom_video_url` serializer and an `add_page_siblings` serializer as well in ab1f7db.
