### ISSUE TITLE
Include developer_id in the post/page serializer 

### ISSUE THREAD

**Issue by jrobson153** [funkhaus/vuepress#17]
This would be handy to use to test things like "is this the home page" or "is this the project-grid page". I wanted it for breadcrumbs.

**Comment by SaFrMo** [comment]
Moving to [Rest-Easy issues](https://github.com/funkhaus/Rest-Easy/issues/4)

**Comment by SaFrMo** [comment]
Fixed in 2b5625c in Vuepress - better to use a custom Rest-Easy filter than change Rest-Easy itself in this case.
