### ISSUE TITLE
Be able to retrieve jsonData from remote source

### ISSUE THREAD

**Issue by SaFrMo** [funkhaus/vuepress#21]
Really useful for debugging - be able to get jsonData from local install of Wordpress or remote source

**Comment by SaFrMo** [comment]
@jrobson153 - Any thoughts on how to implement this? Wanted to talk it through some before setting it up. Thanks!

**Comment by jrobson153** [comment]
@SaFrMo yea, there are a bunch of ways we can do it and I want to go for the least disruptive. I think no matter what the ideal scenario is to just have a plugin settings page where we can just have a checkbox that's like "Site API Proxy" or something like that and put in a URL. 

My first thought is to do this 100% in Rest Easy, maybe inside the [rez_build_all_data()](https://github.com/funkhaus/Rest-Easy/blob/master/builders.php#L7) function we can detect if that setting is on and if so just skip all the internal stuff and make a [wp_remote_get()](https://codex.wordpress.org/Function_Reference/wp_remote_get) call to the proxy server and return the data.

Seems like kind of a strange way to accomplish this I know, but it would essentially be one small section of code handling the proxy and everything after that would work exactly the same. Any other solution I think gets into writing a bunch of logic into our front end code, adding bloat etc.

Thoughts?

**Comment by SaFrMo** [comment]
@jrobson153  Yep, that makes sense to me! Ditto with only seeing overcomplicated solutions with any front-end code - the sooner we can modify how the data is actually requested, the better, and Rest-Easy seems like the right place to do that.

Closing this issue and opening one in [Rest-Easy](https://github.com/funkhaus/Rest-Easy/issues/6).
