### ISSUE TITLE
Add hamburger toggle state and mutation

### ISSUE THREAD

**Issue by SaFrMo** [funkhaus/vuepress#26]
This is something we use in 99% of sites, so it'd save some time to include `state: { menuOpened: false }` and 

```
mutations: {
        'TOGGLE_MENU': state => {
            state.menuOpened = !state.menuOpened
        }
}
```

in `src/store/index.js`.

**Comment by jrobson153** [comment]
When we add this, let's do it as `OPEN_MENU` and `CLOSE_MENU`. I think the best practice is to have the component that runs the mutation be in charge of the toggle logic.

**Comment by SaFrMo** [comment]
Added in 4b1072a
