### ISSUE TITLE
Move ot SASS Media Query for Breakpoints

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/vuepress#29]
Discussed the way to do breakpoints tonight with John a lot. I've never liked the  JS way of adding classes to the body, seems like we are competing against the browsers that way. Also, you need to define them a lot.

So we decided on using SASS for media queries, like this:

```
// Set this is a file called breakpoints.css
$less-than-phone: "only screen and (max-width : 750px)";
$less-than-phone-and-landscape: "only screen and (max-width: 750px) and (orientation: landscape)";

// Then in any CSS file you can simply do
@media #{$less-than-phone} {
    background: red;
}
```

So we should just pre-define all the ones that were in the old breakpoints.css into this new file.

**Comment by SaFrMo** [comment]
This makes sense - we can add these from the old breakpoints.css file:

* `(min-width: 1800px)` as `$cinema`
* `(max-width: 1200px)` as `$laptop`
* `(max-width: 750px)` as `$mobile`
* `only screen and (max-width: 750px) and (orientation: landscape)` as `$mobile-landscape`

I think we should also add:
* `@media only screen and (min-device-width : 768px) and (max-device-width : 1024px)` as `$ipad` (see [here](http://stephen.io/mediaqueries/))

Let me know if you'd like to see difference variable names or values @jrobson153 @drewbaker @lwaldner

**Comment by drewbaker** [comment]
OK cool, but lets not call it `$ipad`, because that is going to change over time. It should be `$less-than-tablet` or something like that. I really think it needs the `$less-than-*` or `$greater-than-*` because that is what is really going on.

**Comment by jrobson153** [comment]
@drewbaker I fully agree with the intention, but `$less-than-mobile` is almost as many characters as `(max-width: 750px)`. Are we saving ourselves any trouble with variables or should we just stick to writing vanilla media queries?

**Comment by drewbaker** [comment]
Ha! OK, well as long as we stick to the logic that everything is less than, we can go to one word.

**Comment by drewbaker** [comment]
`$lt-phone`?

**Comment by drewbaker** [comment]
I put this into Ridley Scott, and I love it. Works really well. I defined it in _vars like this:
https://github.com/funkhaus/ridleyscott.com/blob/master/src/components/parts/CompaniesButton.vue#L68-L77
```
// Break points
$gt-cinema: "only screen and (min-width: 1800px)";
$lt-desktop: "only screen and (max-width: 1100px)";
$lt-phone: "only screen and (max-width: 750px)";
$lt-phone-landscape: "only screen and (max-width: 750px) and (orientation: landscape)";
```

And then can just do this at the end of any `style` section of a component:
https://github.com/funkhaus/ridleyscott.com/blob/master/src/components/parts/CompaniesButton.vue#L68-L77
```
     // Breakpoints
    @media #{$lt-phone} {
        .companies-button {
            left: 70px;
            
            span {
                display: none;
            }
        }
    }
```

It's great, and I think the way we should all do breakpoints from now on, pending you input obviously.

**Comment by SaFrMo** [comment]
Looks great @drewbaker ! Definitely agree about the nesting - one or two levels is the best place to be for sure. I see a little more nesting in animations (`@for $i` loops with `nth-child(#{ $i })`, for instance), but most of my normal styling on Machine was fine one or two levels deep.

**Comment by SaFrMo** [comment]
Added and documented in d2a1e14
