### ISSUE TITLE
Add body class when on touch devices

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/vuepress#30]
We need to come up with a way of knowing when the website is being displayed on a touch device, mostly to know when to have hover effects.

Ideally, we add `is-touch` or `not-touch` classes to the body.

We used to do this with `wp_is_mobile()` in PHP, but what is the new better way in Vue? 

This was an interested read: https://css-tricks.com/touch-devices-not-judged-size/

But this is a very good overview of the issues: http://www.javascriptkit.com/dhtmltutors/sticky-hover-issue-solutions.shtml

The real problem is the increasing use of devices that are both touch screens and have mouse pads or stylus pens. So that above article has a scenario called #4 that seems like the anser, but it involves watching for the use of `touchstart` or a `mouseover` event all the times, so might be too intensive. What do you guys think?

**Comment by SaFrMo** [comment]
@drewbaker I added an `isMobile` property to the `site` field in Rest-Easy [here](https://github.com/funkhaus/Rest-Easy/commit/56ad43f4aa0f94c46a821551bae1eaf71c9678e7), then added an `is-touch` or `not-touch` to the body class in afc88f5. Should work out of the box now!
