### ISSUE TITLE
A way to move [short-code] HTML/CSS/JS into Vue, instead of WordPress PHP

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/vuepress#31]
If we are embracing Vue for all frontend tasks, it seems like we should come up with a way to deal with shortcodes in a Vue way. Like what about galleries used in a post?

This is an interesting read: https://www.codementor.io/mblarsen/wordpress-shortcodes-vuejs-vue-js-5gv4op8sm

Or maybe this helps: https://wordpress.stackexchange.com/questions/272550/vue-js-ajax-shortcode

**Comment by jrobson153** [comment]
This has now been solved with the addition of the [`wp-content`](https://github.com/funkhaus/fh-components/tree/master/src/wp-content) component to fh-components.
