### ISSUE TITLE
Include example of how to redriect to first child

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/vuepress#32]
In router.php I wanted to redirect to first child, a common use case. How do I do that? Would be good to make that part of the boilerplate.

**Comment by SaFrMo** [comment]
@jrobson153 @drewbaker We should be fine without having to edit anything in the router/index.js file - take a look at [this section](https://github.com/funkhaus/vuepress#advanced-routing) of the readme, specifically: 

```php
path_from_dev_id('your-developer-id') => array(
        // Redirect to a path - in this case, to the path of the first child
        'redirect'		=> get_child_of_dev_id_path('work')
    )
```

So you can paste this in your `functions/router.php` file:

```
path_from_dev_id('dev-id-to-be-redirected') => array(
        // Redirect to a path - in this case, to the path of the first child
        'redirect'		=> get_child_of_dev_id_path('dev-id-to-be-redirected')
    )
```

Utility functions for things like `get_child_of_dev_id_path` are documented [here](https://github.com/funkhaus/vuepress#utility-functions). Let me know if that solves the issue!

**Comment by drewbaker** [comment]
I tried:
```
            path_from_dev_id('companies')	 => array( 'redirect', get_child_of_dev_id_path('companies') ), // Redirect to first child
```

And it didn't work.

**Comment by SaFrMo** [comment]
@drewbaker 'redirect' and the new path need to be a key-value pair:

`path_from_dev_id('companies')	 => array( 'redirect' => get_child_of_dev_id_path('companies') )`
