### ISSUE TITLE
Update router.php examples to be more real-world

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/vuepress#33]
I have a structure like this:

```
* Companies (redirects to first child)
    * RSA
        * Work Detail
        * Work Detail
```

So what would the route be? I'm guessing this:
`path_from_dev_id('companies', '/:detail/:video')	    => 'VideoDetail',`

This is a common use case, so lets include an example of this. Seems to me the examples should be:

```
Home
Directors (redirect to first child)
Directors > Director Detail
Directors > Director Detail > Reel Grid
Directors > Director Detail > Reel Grid > Video Detail
About
Contact
Contact > Region (redirect to parent)
```

I think this would cover 99% of the sites we do.

**Comment by SaFrMo** [comment]
Added in 73e0920
