### ISSUE TITLE
Define available fonts someplace

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/vuepress#38]
In the past, I've always liked defining what fonts were available and what weights you could use. Where is a good place to define those now? Maybe in the new font-loader PHP file? I was going to put it in _vars.scss, but it's probably not a natural place to look for font information...

```
/*
Available Fonts & Weights:
    font-family: Helvetica, sans-serif;
        font-weight: 400;
        font-weight: 500;

    font-family: 'Times New Roman', serif;
        font-weight: 500;
        font-weight: 700;
*/
```

**Comment by drewbaker** [comment]
I put this in the top of `font-loader.php` for now, I like it:

```
<?php 
/*
    Available Fonts & Weights:
        font-family: Helvetica, sans-serif;
            font-weight: 400;
            font-weight: 500;

        font-family: 'Times New Roman', serif;
            font-weight: 500;
            font-weight: 700;
*/
?>
<script>
WebFontConfig = {
    ...

```

**Comment by jrobson153** [comment]
@drewbaker @SaFrMo  I think the better solution here is to have the family and a set of weights available in the vars file so you never have to think about it. Something like this for the family:

```sass
$primary-font: Helvetica, sans-serif;
$secondary-font: Georgia, sans-serif;
```

Then you can use those var names throughout and easily change them globally. For weights, I'm thinking we can put in a set of vars that will help us relate a particular weight to the way they would be shown in illustrator. Something like this:

```sass
$thin: 100;
$extra-light: 200;
$ultra-light: 200;
$light: 300;
$normal: 400;
$regular: 400;
$medium: 500;
$semi-bold: 600;
$demi-bold: 600;
$demi: 600;
$bold: 700;
$extra-bold: 800;
$ultra-bold: 800;
$black-weight: 900;
$heavy: 900;
```

Then we don't need that comment style documentation, we can just get used to these names. Thoughts?

**Comment by drewbaker** [comment]
Well the main reason I document the fonts, is so that my future self knows that the italic/heavy style is not available to use (often not turned on in typekit). So when you have two or three font choices, I think your solution wouldn’t be clear as to which weights/styles were available. Mine wouldn’t tell you what styles either actually...

**Comment by jrobson153** [comment]
Hmmm, maybe this is best suited for the README then, where we document the expected page structure for each site?

**Comment by drewbaker** [comment]
Yeah forgot about the readme file, perfect spot for it! I'll do that, and then we can add it to the boilerplate.

**Comment by drewbaker** [comment]
This is where I ended up, might be worth adding something like it to the readme: https://github.com/funkhaus/ridleyscott.com
