### ISSUE TITLE
How to use SCSS vars in views?

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/vuepress#39]
I have this in FrontPage.vue:

```
<style lang="scss">
    .slideshow {
        position: relative;
        background-color: $black;
        height: 70vh;
    }
</style>
```

And it gives this error:
```
Error: Module build failed: 
        background-color: $black;
                     ^
      Undefined variable: "$black".
      in /Users/drew/Local Sites/ridley-scott/app/public/wp-content/themes/ridleyscott2018/src/components/templates/FrontPage.vue (line 38, column 23)
```

**Comment by SaFrMo** [comment]
Include the `@import` statement and you should be good:

```
<style lang="scss">
    @import 'src/styles/your-partials-file';

    .slideshow {
        position: relative;
        background-color: $black;
        height: 70vh;
    }
</style>
```

You don't the the leading underscore or `.scss` when importing like this.

**Comment by jrobson153** [comment]
@drewbaker the one-liner that will always stay the same for our purposes is:

`@import 'src/styles/vars';`

Use that whenever you need to tap into shared variables and mixins. It would be handy to have this globally pre-loaded through all components, but for complicated webpack reasons it's not easily done. For more info on this, check out [this thread](https://github.com/vuejs/vue-loader/issues/328). 

Keeping this issue open to remind ourselves to document this in the readme.

**Comment by drewbaker** [comment]
OK, got it. Sucks, but I read that thread you linked and it seems like this will get fixed eventually.

**Comment by drewbaker** [comment]
I get an error when doing the import:
`Error: Cannot find module "-!../../../node_modules/css-loader/index.js?sourceMap!./src/styles/_vars.scss"`

**Comment by drewbaker** [comment]
I get an error when doing the import:

`Error: Cannot find module "-!../../../node_modules/css-loader/index.js?sourceMap!./src/styles/_vars.scss"`

**Comment by drewbaker** [comment]
Never mind, I was missing the lang="scss" part. This worked:
```
<style lang="scss">
    @import 'src/styles/vars';
```

**Comment by drewbaker** [comment]
There doesn't seem to be any downside to just adding `@import 'src/styles/vars'` into all the templates. We should certain include that in Default.vue, as I use that as the scaffold for all my files.

**Comment by SaFrMo** [comment]
^ Added that line in 6d89824 Default.vue

**Comment by SaFrMo** [comment]
Documented in 6230260 - closing issue.
