### ISSUE TITLE
base.scss or _base.scss?

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/vuepress#40]
The file is _base.scss, but we import base.scss. Why?

https://github.com/funkhaus/vuepress/blob/master/src/App.vue

**Comment by SaFrMo** [comment]
That's a SASS convention - you need the leading underscore to show that the file is a partial meant to be imported elsewhere. See [this page](http://sass-lang.com/guide) under "Partials" and "Import."

**Comment by drewbaker** [comment]
Ok, so the _ is a sass thing, so why do we import base.scss then? Does the compiler know to add the underscore to it? I think it’s a typo.

**Comment by jrobson153** [comment]
@drewbaker it's not a typo, this is how sass requires you to do it. Partials **must** be named with a leading underscore, and when imported they **must** be referred to without the underscore.

Can't say I agree with it, but that's the way it is. As Sander mentioned for more info you can read the [import section of this page](http://sass-lang.com/guide).

**Comment by drewbaker** [comment]
OK that’s what I wanted to know. You have to import without the underscore. Super strange they did that, the import statement is a path that doesn’t exist!
