### ISSUE TITLE
Vuepress boilerplate wishlist

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/vuepress#46]
Just a running list of things I think we should add into the boilerplate

- [x] SVG image component, with base-path
- [x] Break out functions.php into separate files for meta, shortcodes. To discuss.
- [x] Add gallery shortcode into boiler plate
- [x] Better router examples
- [x] Add all fh-components to main.js, but comment them off by default
- [x] Add Hamburger to boilerplate
- [x] Add menu-panel to boilerplate, with click blocker 
- [x] Work detail with stage fh-component
- [x] Work grid example in boilerplate
- [x] Archive example with grid and news menu in boilerplate
- [x] Add `@import 'src/styles/_vars;'` to Default template
- [x] Update readme with font boilerplate
- [x] Add breakpoints in to vars.scss, and add boilerplate to templates
- [x] Add referralPath features (see Ridley) into boilerplate
- [x] Add referralScrollPos into boilerplate (and make it load to that if navigating back to that referral). Need to discuss this, basically we want to go back to the same place in a work grid.
- [x] Include commonly used transitions (fade out, crossfade, slide left/right/up/down)
- [x] Swipe handlers for gallery
- [x] Connect this repo to the Flywheel template site. Future we can just start with that template site always.
- [x] Add infinite scroll to Archive pages by default (maybe this? https://github.com/ElemeFE/vue-infinite-scroll)
- [x] Update admin.css and login.css with new boilerplate
- [x] Add Funkhaus badge to the contact page
- [x] Add google analytics codes
- [x] Update page title on route change
- [x] Add example of running `nl2br()` on a meta text field 
- [x] Add custom video meta field to attachment panel. Use the same meta key as on post/pages by default.

**Comment by SaFrMo** [comment]
Added fh-components to main.js, commented out ones not used in boilerplate in bb7a511

**Comment by SaFrMo** [comment]
Added hamburger to fh-components in 1.2.17 and added to Vuepress in 6e70de5

**Comment by SaFrMo** [comment]
@drewbaker Regarding `Swipe handlers for gallery` - I end up just using Hammer.js for swipes and [vue-awesome-swiper](https://github.com/surmon-china/vue-awesome-swiper) for click-and-drag slideshows. I think relying on those will be better than building our own - thoughts on that? Marking complete in the meantime.

**Comment by drewbaker** [comment]
The problem with the current swipe handling on Ridley Scott is that it won’t allow vertical scrolling if you touch the gallery. Maybe we should have a prop for each gallery that allows us to set “vertical swipes” or “horizontal swipes”?

**Comment by SaFrMo** [comment]
Makes sense - looking at that now, it looks like I didn't add in Hammer or Swiper on that one anyway. Hammer has an option where it can listen for just left/right movement, so that might solve the problem wth the Ridley Scott gallery. In the long-term, though, the vertical/horizontal swipe prop is a good idea!

**Comment by SaFrMo** [comment]
Removing "social links" from here abd moving to [fh-components wishlist](https://github.com/funkhaus/fh-components/issues/2) - that's more under the scope of that repo.

**Comment by jrobson153** [comment]
for the gallery swipe issue, I have been using [vue-touch](https://github.com/vuejs/vue-touch/tree/next) which is essentially just hammer.js wrapped up in a vue components, maintained by some of the vue core team.

It just works like this, so up and down is no problem:
`<v-touch @swipeleft="someMethod" @swipedown="otherMethod">...</v-touch>`

vue-awesome-swiper looks really good too, we should probably pick one that we all like and stick with it.

**Comment by SaFrMo** [comment]
`referralPath` added in 4f1ad56.

I saved the entire `from` route object as `$store.state.referral` and made a getter called `referralPath` to return `$store.state.referralPath.fullPath` or an empty string. 

This'll be a more robust way to refer to path names, variables, etc. from the previous page if we want them.

**Comment by SaFrMo** [comment]
Marking 'commonly used transitions' item as complete - discussion can continue in #49.

**Comment by SaFrMo** [comment]
Moving referralScrollPos discussion to #52.

**Comment by SaFrMo** [comment]
* Break functions.php out except shortcodes, metafields, images

**Comment by SaFrMo** [comment]
Broke out functions file in 74ecb39

**Comment by SaFrMo** [comment]
Improved router examples in 73e0920

**Comment by SaFrMo** [comment]
Marking tasks that already have individual issues as complete (Google analytics code, page title on route change, video metafield).

**Comment by SaFrMo** [comment]
Creating separate issue for infinite scroll, marking item in list as complete

**Comment by SaFrMo** [comment]
Added separate issues for remaining tasks, closing this issue.
