### ISSUE TITLE
Add in our own Google Analytics tracking code

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/vuepress#51]
So for all new websites it would be great if we had a Funkhaus tracking code on it, and the clients gets added. It’s just important for us to now know how all our websites are performing and capture that data.

**Comment by drewbaker** [comment]
Should go in Index.php. Investigate how to track all the client sites with one UA code for Funkhaus. Maybe like this:

`ga('create', 'FUNKHAUS_UA_CODE, 'auto', {'name':'Client Site Name'});`

**Comment by SaFrMo** [comment]
@drewbaker Has this been added in `parts/ga-tracking.php`? It looks like it might've been - if so, we can close this issue. Thanks!
