### ISSUE TITLE
Test for common "go-live" mistakes

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/vuepress#60]
This might be outside the scope of a theme, but it would be cool if part of our deployment process checked for common things that get left out of the go live process.

![screen shot 2018-01-09 at 4 34 37 pm](https://user-images.githubusercontent.com/475015/34750279-28178434-f55b-11e7-9e5d-5ba5b0b73016.png)

**Comment by SaFrMo** [comment]
I think this does fall outside the scope of Vuepress, but it'd be a great in-house Funkhaus script. I'm going to close this for now but we should keep this in mind for our future workflow.
