### ISSUE TITLE
Add example of nl2br on a text field

### ISSUE THREAD

**Issue by SaFrMo** [funkhaus/vuepress#61]
@drewbaker, I haven't run into this yet, so could you put this in the readme or wherever else would be best? Thanks!

**Comment by drewbaker** [comment]
OK, I've been thinking about this, I think in general the more examples we can provide for Rest-Easy filters the better. So it seems to me in Rest-Easy we should have a `filter-examples.php` that we just use to put all the useful snippets we come up with, we just make sure to keep it well structured and inline documented.

What do you think?

**Comment by SaFrMo** [comment]
I like that idea a lot! I'd personally lean more toward a separate .md file or examples in the Rest-Easy readme rather than another php file, but that'd be a useful thing to have no matter what. Any strong preference @drewbaker ?

**Comment by drewbaker** [comment]
Well I just want it to be super easy to cut and paste and add too, so if you prefer an .md file for that then fine.

**Comment by drewbaker** [comment]
Done.
