### ISSUE TITLE
Errors From parts/ga-tracking.php

### ISSUE THREAD

**Issue by lwaldner** [funkhaus/vuepress#62]
Did a fresh install of vuepress and got the following errors. I commented out ga-tracking.php for now. 

- Missing semicolon on line 6
- Missing opening ? on line 24
- "Invalid Arguments for foreach" on line 5

**Comment by SaFrMo** [comment]
Fixed in d2cbb43 - I haven't tested it yet, so can you paste in the new contents of the file and see if it works @lwaldner ? Thanks!

**Comment by SaFrMo** [comment]
Tested and works!
