### ISSUE TITLE
Add "hide from post gallery" checkbox to image meta

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/vuepress#72]
Dealing with "top slideshows" on a page or post, that show all the images attached to this page/post is a very common thing we do. Problem is, then it pulls in images that are embedded in the content as well. So a lot of times, we will end up having a child page that just holds the images for the the slideshow.

It seems having a checkbox on image meta that either "hides from post gallery" or perhaps "show in post gallery" would be a very common thing that we could then use.

What do you guys think? Is this common enough to add to the theme by default?

**Comment by drewbaker** [comment]
Spoke with John, and this is a bad idea. We really should have a "select post gallery images" meta box that works similar to the way the second featured image meta box works. I will investigate.

**Comment by drewbaker** [comment]
Posted this today as an attempt to do this legit: https://stackoverflow.com/questions/48818952/wordpress-add-gallery-overlay-to-a-metabox-using-wp-media

**Comment by SaFrMo** [comment]
@drewbaker Seeing a new response - https://stackoverflow.com/a/48877248/3856675 - have you looked at this solution yet? I haven't had a chance to but am curious to see if it'd work for us.

**Comment by drewbaker** [comment]
Working on this today!

**Comment by drewbaker** [comment]
So the SO post was only sort of useful, it got me a little bit of the way there, but the overlay it opens is pretty janky, and not intuitive. I just don't know enough about how the wp.media JS library works. I think it's built on backbone, so if you guys know that, maybe you can help?

**Comment by drewbaker** [comment]
Using ACF to solve this now.
