### ISSUE TITLE
Image preloader

### ISSUE THREAD

**Issue by SaFrMo** [funkhaus/vuepress#73]
We're running into a problem where using `v-if` on `responsive-image`s or their containers results in some shaky performance, since images aren't loading until they're added to the DOM. Images are therefore often being loaded as they're fading or translating in, creating a bit of jitter.

Thoughts on how to handle this:

* A special directive for `responsive-image`s that loads the image, then runs a normal `v-if` on the element. Something like:

```
<responsive-image v-preload="renderCondition" :object="..."/>
```

* Learning more about how `v-if` works in Vue and seeing if we can find a workaround to preload images.
* Using `v-show` on `responsive-image`s and their containers instead of `v-if`. Not ideal, since `v-if` seems a bit more powerful when it comes to transitions.

Any other thoughts @jrobson153 @lwaldner @drewbaker ?

**Comment by jrobson153** [comment]
I think this might be best suited as just a utility similar to [imagesLoaded](https://www.npmjs.com/package/imagesloaded) but specifically meant to deal with our attachment objects that come from Rest Easy. Here's what I imagine the interface might be:

```js
import { preloader } from 'src/utils/shared'

export default {
  async mounted () {
    const featuredImg = this.$store.getters.post.featuredAttachment

    // forces the browser to load this image and store in cache
    await preloader.image(featuredImg)

    console.log('Featured image is now loaded!')
  }
}
```

It would take a little customization each time you use it, but I like the idea of having control over what's going on. What do you think?

**Comment by SaFrMo** [comment]
I like that - we could allow you to pass complete Rest-Easy objects as well as common use-cases:

```js
preloader.image(attachmentObject) // Preloads attachment object
preloader.image(postObject) // Preload featured image from given post object
preloader.image([array, of, post, or, attachment, objects]) // Ditto for array of (mixed?) objects
```

**Comment by drewbaker** [comment]
What about anytime something gets added to the store, we look for all image objects, and preload them? That would probably end up in way too many images being preloaded, but it's a start.

I'd love to come up with something that is super easy to use. Is it possible to do something like this?

```
    export default {
        preload: {
             featuredImages() {
                 return this.$store.getters.post.featuredAttachment
             },
            gridImages() {
                 // This would then loop through all the posts and any image URL it finds, preload it.
                 return this.$store.getters.post.related.siblings
             },
        },
        components: {
            'project-block': require('src/components/GridBlock.vue')
        },
        computed: {
            allBlocks() {
                let children = this.$store.getters.post.related.children

                // Remove 'slideshow' child from loop
                _remove(children, (obj) => {
                    return obj.developerId === 'slideshow'
                })
                return children
            }
        }
    }
```

**Comment by SaFrMo** [comment]
@drewbaker The idea of loading images from any object in the store is definitely a thought, but on grid or archive pages it'd end up in a pretty heavy pageload - I'm not sure how scalable that'd be.

Also, the `preload` function you're describing there basically the same as the way @jrobson153 was using `mounted` [here](https://github.com/funkhaus/vuepress/issues/73#issuecomment-3662799590) - I see where you're going but I don't think it's different enough from `mounted` to justify its own top-level property.

(And come to think of it, I'm not even sure how you'd reliably add and work with a new top-level property like that - do you know, @jrobson153 ?)

**Comment by drewbaker** [comment]
I see what your saying about a `preload` being the same as `mounted`. So if we could use what John wrote like this, that would be super easy and good.

But I do like the idea of it being part of `responsive-image` by default, that makes that component even better.

```
    import { preloader } from 'src/utils/shared'
    export default {
        mouted: {
             let preloadThese = {
                          this.$store.getters.post.featuredAttachment,
                          this.$store.getters.post.related.siblings // Would find any attachment object, one deep
             }
             preloader(preloadThese)
        }
    }
```

**Comment by jrobson153** [comment]
Yea, @drewbaker I like the idea of trying to just make it super simple and have it be able to figure out what to preload as it goes.

The tricky part of the pseudocode you just wrote is that all those siblings in `related` could be carrying tons of attached images as well as featured, and each of those comes in many different sizes. Which version(s) is the preloader actually supposed to preload?

The responsive-image idea is really good too, this is probably the cleanest interface we could possibly get:

`<responsive-image preload="true" size="medium" :object="object" />`

The problem there is that we really need the preload _before_ this element even exists, so it's not super helpful to call it on the component itself. It really needs to happen within the logic of the containing component I think, just not sure what the cleanest way is.

**Comment by drewbaker** [comment]
OK, how about this then?

```
    import { preloader } from 'src/utils/shared'
    export default {
        mouted: {
             let preloadThese = {
                          this.$store.getters.post.featuredAttachment,
                          this.$store.getters.post.related.siblings
             }
             preloader(preloadThese, ['full', 'grid-thumbnail']) // You can pass in an array of sizes to target
        }
    }
```

As for preloading all of the related, I think you'd actually want it to preload everything if you told it to. Its on the dev to be specific with it. I think there are scenarios where I'd want to preload every attached image in a grid, like on a property website were each grid block had a slideshow preview on it. Or do we have a depth parameter? Like `preloader(preloadThese, ['full', 'grid-thumbnail'], 3)` which will only go 3 levels deep for each image object passed in?

**Comment by SaFrMo** [comment]
I think that's a good option, @drewbaker - the ideal definitely feels like @jrobson153 mentioned, with a prop allowing us to preload a responsive-image's src when that responsive-image hasn't necessarily loaded yet, but the solution @drewbaker will work great.

One alternate method I can think of is to never use `v-if` on a `responsive-image` when we want that image to preload - for example, instead of the standard

`<responsive-image v-if="condition" ... />`

we could use `v-show`:

`<responsive-image v-show="condition" .../>`

Then, in order to keep both (a) preload the image and (b) prevent the img element from appearing in the DOM until needed, `responsive-image` could look more like this:

```
<template>
  <div class="rsp-image-module">
    <img v-if="$el.style.display != 'none'" :src="...">
  </div>
</template>

<script>
export default {
  props: {
    imageSrc: { ... }
  },
  mounted(){
    // preload imageSrc here 
    // this will always run, since the only thing being v-if'd is the img element itself
  }
}
</script>
```

The more I think about it, the more I like @drewbaker 's method, since that can allow for consecutive fetches like the cache-crawler instead of one big top-heavy load like we might get with the modified `responsive-image` element.

**Comment by jrobson153** [comment]
I've added a super basic version of this in https://github.com/funkhaus/vuepress/commit/d4844a61b4b8666e629a44e19d1fc47a97e52376

Basically it just accepts either an image URL or a rest-easy serialized object and returns a promise that resolves once the image is loaded. I created one for videos as well, they are both now located in the `src/utils/shared.js` file.

I've found that a lot of these preloading issues can just be solved by using `v-show` rather than `v-if` in certain places. The next time one of us encounters a situation where more advanced preloading is needed let's come back to this and see if the basic version I've added can do the trick or if something more comprehensive is needed.

**Comment by SaFrMo** [comment]
@johndigital @lwaldner @drewbaker John's addition and using `v-show` instead of `v-if` like Luke mentioned is fixing my image-loading issues. I'm down for closing this issue if y'all are!

**Comment by johndigital** [comment]
@SaFrMo I think the one really common case that v-show can't solve is preloading images for a slideshow so you don't get the flash of the color background.

@drewbaker did you want to go through how to solve that for Bernards using the preload utility that I added and then we can decide if we need something more robust?

**Comment by SaFrMo** [comment]
@johndigital Good point on the slideshow issue - maybe we can include a `preloadImages` prop on the slideshow component to allow preloading images?

**Comment by johndigital** [comment]
I think the slideshow is probably a little too generic now since you can pass literally any type of data into it and then define the markup in a template. We could do some kind of crazy search logic to try and find and preload any and all images that get passed into the slideshow, but realistically just using the utility I wrote to do a manual preload from the component containing the slideshow would look like this:

```js
// in mounted hook
this.slides.map(slide => {
    return preloadImg(slide.featuredAttachment, 'medium')
})
```

So it seems pretty reasonable to just do that instead.

**Comment by SaFrMo** [comment]
Works for me!

**Comment by johndigital** [comment]
Yep I agree, I haven't run into any scenarios that need anything more advanced than that. Closing!
