### ISSUE TITLE
Empty $store.getters.post if loading

### ISSUE THREAD

**Issue by SaFrMo** [funkhaus/vuepress#80]
I ended up writing this in `$store.getters` on my latest site:

```js
        post: state => {
            if( !state.loaded ){
                return {}
            }

            // This is a "post" in the sense of a WordPress post - the first result of the Loop
            return _get(state.loop, '[0]', {})
        },
```

This way, you don't see any flashes of the previous page's content before the new page loads.

Two questions:
1. Any problem with adding this in as-is to the boilerplate?
1. Should we create a boilerplate fallback component to handle loading, or should that be on a per-site basis?

**Comment by drewbaker** [comment]
I can't talk to the correct "vue" way to do it, but our boiler plate shouldn't show the wrong content when loading, that is for sure. So if this is the bets way to handle this, then lets do it.

**Comment by drewbaker** [comment]
Should we then have a `getter` for related? So that we can handle the same "flash of wrong content" for things like grids?

**Comment by SaFrMo** [comment]
@drewbaker I think the related getter can be an extension of the post getter - so for related posts, you'd do:

```js
computed: {
  related(){
    return _get(this.$store, 'getters.post.related', {})
  }
}
```

That'll default to an empty object while the page is loading and return the correct result when it's available. To do the same thing for children:

```js
computed: {
  children(){
    return _get(this.$store, 'getters.post.related.children', [])
  }
}
```

**Comment by jrobson153** [comment]
We just chatted about this here in Ithaca, I think there are times where you want the to still see the current content while new content is loading in but at least 90% of the time the functionality we want is what @SaFrMo has described above where it returns an empty object during load.

Let's add that code into the boilerplate and if we encounter a scenario where we need it to function the old way we can just revert it manually by deleting those 3 lines.

**Comment by drewbaker** [comment]
If I wanted the content o show while losing, couldn’t I just get it out of the $store, rather than using a getter?

**Comment by jrobson153** [comment]
yep, that's definitely something to be aware of because this solution won't protect you when you're using the actual loop (showing a grid of directors for instance.)

**Comment by drewbaker** [comment]
That’s good I think. Basically if I want to have hidden page loading, i use the getter. Gives us options.

**Comment by SaFrMo** [comment]
Added in 5c4cd32
