### ISSUE TITLE
Add method to get parent URL

### ISSUE THREAD

**Issue by SaFrMo** [funkhaus/vuepress#83]
Maybe in App.vue:

`this.$route.fullPath.replace(/\/[^\/]+\/?$/, '/')`

Removes the last subdirectory of a URL (`/parent/child` becomes `/parent/`)

**Comment by drewbaker** [comment]
Is it too "WordPressey" if we had a method that could get parent, grand parent etc? Like `getAncestorPath(depth)` where `depth` is equal to how high up to go? So `getAncestorPath(1)` would be the parent, `getAncestorPath(2)` would get the grand parent? Really this is going to be used for close buttons on video detail pages the most I think (and sometimes the structure will be parent>reel>detail`).

**Comment by SaFrMo** [comment]
Definitely, I like that idea! We could repeat the function above the number of times that the user passes in. I'll add that and the documentation later today.

**Comment by SaFrMo** [comment]
@drewbaker @jrobson153 @lwaldner Turns out there's a Vue way to do this already!

`<router-link to="../" append>Up one level</router-link>`

The `append` prop adds the given `to` value to the end of the current URL, so you can just add as many `../`s as you need. For example:

```
<router-link to="../" append>Go to parent</router-link>
<router-link to="../../" append>Go to grandparent</router-link>
```

I'll close this issue in the next couple days since we don't need to add anything for this!

**Comment by SaFrMo** [comment]
Closing this! Hope y'all have seen, @drewbaker @jrobson153 @lwaldner , it's saved me a lot of headache with breadcrumbs already!
