### ISSUE TITLE
Remove (or at least comment out) related gatherers 

### ISSUE THREAD

**Issue by SaFrMo** [funkhaus/vuepress#89]
For the past couple sites I've run into some pretty long load times because of the default `add_page_siblings` function. (ETC, for example, specifically wants a work grid with ~600 items, all of which are going to serialize their ~599 siblings right off the bat.) Let's comment that out in the boilerplate so we have to be more selective when serializing siblings.

**Comment by SaFrMo** [comment]
Fixed in 29b4035

**Comment by drewbaker** [comment]
Sander I wonder if we make this a setting on the developer ID page? Because you generally only need that sibling thing on detail pages.
