### ISSUE TITLE
CSS source maps?

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/vuepress#91]
Would we be able to some CSS source maps with VP easily? Would be handy to track down which file a CSS rule is set in.

**Comment by SaFrMo** [comment]
Looks like this should be possible - https://github.com/vuejs-templates/webpack/issues/123

I can check into it more in the next couple days!

**Comment by SaFrMo** [comment]
Added in 239764d! Some people have had bugs with relative paths in sourcemaps - if anything breaks a dev build you can just remove both occurrences of `?{"sourceMap":true}` from `webpack.config.js`.
